#version: '3'
services:
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
            - sail
