Seleccionar todo		
	afiliados		
	afiliados_coberturas_saluds		
	afiliados_convivencias		
	amparos		
	autorizacions		
	cartas_imagenes		
	carta_autorizaciones		
	coberturas_salud		
	conclusiones		
	datos_basicos		
	datos_basicos_hijos		
	departamentos		
	direcciones_viviendas		
	empleos_afiliados		
	estados_civiles		
	failed_jobs		
	filtros_pdfs		
	firmas		
	hallazgos_observaciones		
	hechos_ocurrencias		
	imagen_reclamantes		
	informes		
	migrations		
	model_has_permissions		
	model_has_roles		
	motivos_muerte		
	muertes_origen		
	municipios		
	notificaciones_checklists		
	paises		
	password_resets		
	password_reset_tokens		
	permissions		
	personal_access_tokens		
	personas_afiliadas		
	photos		
	reclamantes		
	reclamantes_afiliados		
	roles		
	role_has_permissions		
	siniestros		
	tipos_afiliaciones		
	tipos_de_propiedades		
	tipos_de_viviendas		
	tipo_de_convivencias		
	tipo_documentos		
	users		
	verificaciones